// frontend/Oibay/src/app/components/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../../../auth.service' 
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  imports:[RouterModule,ReactiveFormsModule,CommonModule],
  standalone: true,
})

export class LoginComponent {
  loginForm: FormGroup;

  constructor(private fb: FormBuilder, private authService: AuthService) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]], // Обязательное поле и проверка на формат email
      password: ['', [Validators.required, Validators.minLength(6)]] // Обязательное поле и минимальная длина 6 символов
    });
  }

  get email() {
    return this.loginForm.get('email'); // Получаем поле email
  }

  get password() {
    return this.loginForm.get('password'); // Получаем поле password
  }

  async onLogin() {
    if (this.loginForm.valid) {
      try {
        const { email, password } = this.loginForm.value;
        const response = await this.authService.login(email, password);
        console.log('Вход прошел успешно:', response);
        this.authService.saveToken(response.token);
        // Перенаправление на главную страницу
      } catch (error: unknown) {
        const errorMessage = (error as Error).message || 'Неизвестная ошибка';
        console.error('Ошибка входа:', errorMessage);
        alert(`Ошибка: ${errorMessage}`);
      }
    } else {
      alert('Пожалуйста, исправьте ошибки в форме.');
    }
  }
  
}

<div class="login">
    <div class="login-container">
        <h1>
            Войти
        </h1>
        <div class="login-sign-up">
            <div class="login-sign-up-container">
                <p>Новый пользователь?</p>
                <button [routerLink]="['/registration']">
                    Создать учетную запись
                </button>
            </div>
        </div>
        <form [formGroup]="loginForm" (ngSubmit)="onLogin()">
            <div class="login-inputs">
                <label for="email">Почта</label>
                <input id="email" type="text" placeholder="example@gmail.com" formControlName="email">
                <div *ngIf="email?.invalid && (email?.dirty || email?.touched)" class="error-message">
                    <div *ngIf="email?.errors?.['required']">Поле обязательно для заполнения.</div>
                    <div *ngIf="email?.errors?.['minlength']">Неверный формат почты.</div>
                </div>
                <label for="password">Пароль</label>
                <input id="password" type="password" placeholder="ABC@#$!12" formControlName="password">
                <div *ngIf="password?.invalid && (password?.dirty || password?.touched)" class="error-message">
                    <div *ngIf="password?.errors?.['required']">Поле обязательно для заполнения.</div>
                    <div *ngIf="password?.errors?.['minlength']">Пароль должен содержать минимум 6 символов.</div>
                </div>
            </div>
            <div class="login-action-container">
                <div class="login-remember-me">
                    Запомнить меня    
                    <input type="checkbox">
                </div>
                <button>
                    Забыл Пароль?
                </button>
            </div>
            <button type="submit" class="login-btn" [disabled]="loginForm.invalid">
                Войти
            </button>
        </form>
    </div>
</div>

// frontend/react/my-app/src/components/auth/login.tsx
// src/Login.tsx

import React from 'react';
import { useNavigate } from 'react-router-dom'; // Импортируем useNavigate
import { useForm } from 'react-hook-form';
import './login.scss';

const Login: React.FC = () => {
  const { register, handleSubmit, formState: { errors } } = useForm();
  const navigate = useNavigate(); 
  
  const onLogin = (data: any) => {
    console.log('Login data:', data);
  };

  return (
    <div id="login">
      <div className="login">
        <div className="login-container">
          <h1>Войти</h1>
          <div className="subtitle">Hi, welcome back👋</div>
          <div className="login-sign-up">
            <div className="login-sign-up-container">
              <p>Новый пользователь?</p>
              <button onClick={() => navigate('/auth/registration')}>
                Создать учетную запись
              </button>
            </div>
          </div>
          <form onSubmit={handleSubmit(onLogin)}>
            <div className="login-inputs">
              <label htmlFor="email">Почта</label>
              <input
                id="email"
                type="text"
                placeholder="example@gmail.com"
                {...register('email', { required: true, minLength: 6 })}
              />
              {errors.email && errors.email.type === 'required' && (
                <div className="error-message">Поле обязательно для заполнения.</div>
              )}
              {errors.email && errors.email.type === 'minLength' && (
                <div className="error-message">Неверный формат почты.</div>
              )}
              
              <label htmlFor="password">Пароль</label>
              <input
                id="password"
                type="password"
                placeholder="ABC@#$!12"
                {...register('password', { required: true, minLength: 6 })}
              />
              {errors.password && errors.password.type === 'required' && (
                <div className="error-message">Поле обязательно для заполнения.</div>
              )}
              {errors.password && errors.password.type === 'minLength' && (
                <div className="error-message">Пароль должен содержать минимум 6 символов.</div>
              )}
            </div>
            <div className="login-action-container">
              <div className="login-remember-me">
                Запомнить меня
                <input type="checkbox" />
              </div>
              <button type="button" onClick={() => alert('Forgot Password clicked')}>
                Забыл Пароль?
              </button>
            </div>
            <button type="submit" className="login-btn">
              Войти
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Login;
